# Generated by Django 5.0.2 on 2024-05-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_category_image_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plates',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plates',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
