# Generated by Django 5.0.2 on 2024-08-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_plates_description_alter_plates_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plates',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
