# Generated by Django 5.0.2 on 2024-08-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_plates_ingredients_delete_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plates',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
