# Generated by Django 5.0.2 on 2024-04-28 19:38

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('logic', django.db.models.manager.Manager()),
            ],
        ),
    ]
