# Generated by Django 5.0.2 on 2024-05-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymethod',
            options={'verbose_name': 'Paymethod', 'verbose_name_plural': 'Paymethods'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='paymethod',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='paymethod',
            table='PayMethod',
        ),
    ]
