# Generated by Django 5.0.2 on 2024-05-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_paymethod_options_remove_payment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='Orders',
        ),
    ]
